version: '3'
services:
  drone_back:
    build:
      context: ./back/docker
    depends_on:
      - mysql
    volumes:
      - ./back:/code
    ports:
      - "9002:9002"
    links:
      - mysql

  drone_front:
    build:
      context: ./front/
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/code
    ports:
      - "9001:3000"
    links:
      - drone_back

  mysql:
    image: mysql:latest 
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 123